.TH Canto 1 "MAN_DATE" "Version MAN_VERSION" "Canto"

.SH NAME
Canto \- An ncurses RSS reader
.SH DESCRIPTION
Canto is an RSS reader built to be flexible and highly customizable on top of python.

.SH GETTING STARTED
Canto is the client, separate from the fetcher Canto-fetch. In order to update you must invoke canto-fetch on a regular basis. Usually the way to do that is to add a line into your crontab like this:

* * * * * canto-fetch

If you're not a fan of cron, then you can add `canto-fetch -b` to your startup
scripts to have canto-fetch run as a daemon on its own.

After you have your configuration file generated, just run `canto` and it will update for you, if canto-fetch hasn't been run already.

.SH COMMAND LINE USAGE
.TP
-h/--help
Simple help

.TP
-v/--version
Print version

.TP
-u/--update
Update feeds before launching client.

.TP
-l/--list
List all configured feeds

.TP
-a/--checkall
Print number of new items.

.TP
-n/--checknew [feed]
Print number of new items in feed.

.TP
-o/--opml
Print feeds to stdout as OPML file.

.TP
-i/--import [path]
Import feeds from OPML file to your configuration.

.TP
-r/--url [URL]
Add feed at URL to your configuration.

.TP
-t/--tag [tag]
Set tag for feed added with -r

.TP
-D/--dir [path]
Set the configuration directory (default: ~/.canto/)

.TP
-C/--conf [path]
Set the configuration file (default: ~/.canto/conf)

.TP
-L/--log [path]
Set the log file (default: ~/.canto/log)

.TP
-F/--fdir [path]
Set the feed directory (default: ~/.canto/feeds)

.TP
-S /--sdir [PATH]
Set the path to execurl scripts (default ~/.canto/scripts/)

.SH INTERNAL USAGE
Within the program you can use the following (default) keys.
These can be changed in your configuration file by using the
"key" configuration option.

.TP
UP / DOWN or k / j
Select previous or next item. (next_item) (prev_item)

.TP
PGUP / PGDOWN or o / l
Goto previous or next tag. (next_tag) (prev_tag)

.TP
RIGHT / LEFT
Set item unread or read (just_unread) (just_read)

.TP
[ / ]
Cycle through defined filters (prev_filter) (next_filter)

.TP
{ / }
Cycle through defined tag filters (prev_feed_filter) (next_feed_filter)

.TP
- / =
Cycle through defined tag sorts (prev_tag_sort) (next_tag_sort)

.TP
< / >
Cycle through defined tag sets (prev_tagset) (next_tagset)

.TP
:
Goto a specific tag (order of the config) (goto_tag)

.TP
;
Goto a specific visible tag (goto_reltag)

.TP
TAB
Switch focus between list and reader (only useful with dedicated reader space)
    (switch)

.TP
h
Display this man page. (help)

.TP
Space
Read a story (reader)

.TP
g
Use the defined browser to goto the item's URL (goto)

.TP
C / V
Collapse/Uncollapse all tags (set_collapse_all) (unset_collapse_all)

.TP
c
Collapse/Uncollapse current tag (toggle_collapse_tag)

.TP
f
Inline search (inline_search)

.TP
n / p
Goto next/previous marked item (next_mark) (prev_mark)

.TP
, / .
Goto next/previous unread item (next_unread) (prev_unread)

.TP
r / u
Mark tag read/unread (tag_read) (tag_unread)

.TP
R / U
Mark all read/unread (all_read) (all_unread)

.TP
Ctrl+R
Refresh feeds (force_update)

.TP
Ctrl+L
Redraw screen (refresh)

.TP
q
Quit Canto (quit)

.SH READER USAGE
Inside the reader, there are a number of different keys. These can be changed with the "reader_key" configuration option.

.TP
UP / DOWN or k / j
Scroll up/down if content off screen (scroll_up) (scroll_down)

.TP
n / p
goto next/previous item without closing reader

.TP
l
Enumerate links (toggle_show_links)

.TP
g
Choose a link to goto (goto)

.SH CONFIGURATION
The ~/.canto/conf.py file is where all of the configuration is. You can start by
reading http://codezen.org/canto/config . If you're updating from <= 0.6.x then you
should read http://codezen.org/canto/config/#upgrading-from-06x .

.SH FILES
.TP
.I ~/.canto/conf.py
Main configuration file. ~/.canto/conf (without the extension) is also checked
for compatibility.

.TP
.I ~/.canto/log
Everyday log file.

.TP
.I ~/.canto/fetchlog
Canto-fetch log file.

.TP
.I ~/.canto/feeds/
This is the directory where the stories are recorded.

.SH BUGS
I'm sure there are some. If you run into a bug (a crash or bad behavior), then
send please report it. Any of the methods described in
http://codezen.org/canto/contact are acceptable. Also, please include your
configuration and log files with the report.

.SH HOMEPAGE
http://codezen.org/canto

.SH AUTHOR
Jack Miller <jack@codezen.org>
