.TH Canto 1 "MAN_DATE" "Version MAN_VERSION" "Canto"

.SH NAME
Canto \- An ncurses RSS reader
.SH DESCRIPTION
Canto is an RSS reader built to be flexible and highly customizable on top of python.

.SH GETTING STARTED
Canto is the client, separate from the fetcher Canto-fetch. In order to update you must invoke canto-fetch on a regular basis. Usually the way to do that is to add a line into your crontab like this:

* * * * * canto-fetch

If you're not a fan of cron, then you can add `canto-fetch -b` to your startup
scripts to have canto-fetch run as a daemon on its own.

After you have your configuration file generated, just run `canto` and it will update for you, if canto-fetch hasn't been run already.

.SH COMMAND LINE USAGE
.TP
-h/--help
Simple help

.TP
-v/--version
Print version

.TP
-u/--update
Update feeds before launching client.

.TP
-l/--list
List all configured feeds

.TP
-a/--checkall
Print number of new items.

.TP
-n/--checknew [feed]
Print number of new items in feed.

.TP
-o/--opml
Print feeds to stdout as OPML file.

.TP
-i/--import [path]
Import feeds from OPML file to your configuration.

.TP
-r/--url [URL]
Add feed at URL to your configuration.

.TP
-t/--tag [tag]
Set tag for feed added with -r

.TP
-D/--dir [path]
Set the configuration directory (default: ~/.canto/)

.TP
-C/--conf [path]
Set the configuration file (default: ~/.canto/conf)

.TP
-L/--log [path]
Set the log file (default: ~/.canto/log)

.TP
-F/--fdir [path]
Set the feed directory (default: ~/.canto/feeds)

.SH INTERNAL USAGE
Within the program you can use the following (default) keys.
These can be changed in your configuration file by using the
"key" configuration option.

.TP
UP / DOWN or k / j
Select previous or next item. (next_item) (prev_item)

.TP
PGUP / PGDOWN or o / l
Goto previous or next tag. (next_tag) (prev_tag)

.TP
RIGHT / LEFT
Set item unread or read (just_unread) (just_read)

.TP
[ / ]
Cycle through defined filters (prev_filter) (next_filter)

.TP
{ / }
Cycle through defined feed filters (prev_feed_filter) (next_feed_filter)

.TP
h
Display this man page. (help)

.TP
Space
Read a story (reader)

.TP
g
Use the defined browser to goto the item's URL (goto)

.TP
C / V
Collapse/Uncollapse all tags (set_collapse_all) (unset_collapse_all)

.TP
c
Collapse/Uncollapse current tag (toggle_collapse_tag)

.TP
f
Inline search (inline_search)

.TP
n / p
Goto next/previous marked item (next_mark) (prev_mark)

.TP
, / .
Goto next/previous unread item (next_unread) (prev_unread)

.TP
r / u
Mark tag read/unread (tag_read) (tag_unread)

.TP
R / U
Mark all read/unread (all_read) (all_unread)

.TP
Ctrl+R
Refresh feeds (force_update)

.TP
Ctrl+L
Redraw screen (refresh)

.TP
q
Quit Canto (quit)

.SH READER USAGE
Inside the reader, there are a number of different keys. These can be changed with the "reader_key" configuration option.

.TP
UP / DOWN or k / j
Scroll up/down if content off screen (scroll_up) (scroll_down)

.TP
n / p
goto next/previous item without closing reader

.TP
l
Enumerate links (toggle_show_links)

.TP
g
Choose a link to goto (goto)

.SH CONFIGURATION
The ~/.canto/conf file is where all of the configuration is. You can start by using the example config below.

.SH EXAMPLE CONFIG
.sp 1
.nf

from canto.extra import *
import os

if os.getenv("TERM") == "linux":
    browser="elinks \"%u\""
    text_browser = True
else:
    browser="firefox \"%u\""
    text_browser = False

def my_resize_hook(cfg):
    cfg.columns = cfg.width / 70

resize_hook = my_resize_hook
select_hook = set_xterm_title
end_hook = clear_xterm_title

filterlist=[None, show_unread()]

keys['x'] = ["just_read","next_item"]
keys['1'] = search(".*[Ll]inux.*", regex=True)
keys['2'] = search("Obama")

addfeed("Slashdot", "http://rss.slashdot.org/slashdot/Slashdot")
addfeed("OSNews", "http://osnews.com/files/recent.xml")
addfeed("Damn Interesting", "http://www.damninteresting.com/?feed=rss2")
addfeed("Reddit", "http://reddit.com/.rss")

.SH FILES
.TP
.I ~/.canto/conf
Main configuration file. For advanced usage, see the online configuration documentation: http://codezen.org/canto/config

.TP
.I ~/.canto/log
Everyday log file.

.TP
.I ~/.canto/fetchlog
Canto-fetch log file.

.TP
.I ~/.canto/feeds/
This is the directory where the stories are recorded.

.SH BUGS
None known, but it's not outside of the realm of possibility =P.  

.SH HOMEPAGE
http://codezen.org/canto

.SH AUTHOR
Jack Miller <jack@codezen.org>
