.TH Canto-inspect 1 "MAN_DATE" "Version MAN_VERSION" "Canto-inspect"

.SH NAME
Canto-inspect - print content from a feed.

.SH SYNOPSIS
canto-inspect [URL]

.SH DESCRIPTION
Canto-inspect is a custom pretty printer for content from a
feed. It provides a nice layout for the feed XML.

.SH HOMEPAGE
http://codezen.org/canto

.SH AUTHOR
Jack Miller jack@codezen.org
